# Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.2


# Introduction to Tensors

## Creating Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [13]:
scalar.item(), scalar.shape

(7, torch.Size([]))

In [7]:
scalar.detach().numpy()

array(7)

In [8]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX

MATRIX = torch.tensor([[1,2], [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
torch.rand((3, 4))

tensor([[0.7012, 0.7407, 0.7507, 0.2151],
        [0.2238, 0.9750, 0.9068, 0.5006],
        [0.1369, 0.8117, 0.5516, 0.7079]])

In [19]:
torch.ones((1,2))

tensor([[1., 1.]])

In [20]:
torch.zeros((4,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
a = torch.arange(0, 10, 1)

In [24]:
a.device

device(type='cpu')